"""create_history_tables

Revision ID: bf37cdd39cb0
Revises: 185f6bbb7554
Create Date: 2026-08-23 02:40:58.996679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf37cdd39cb0'
down_revision: Union[str, Sequence[str], None] = '185f6bbb7554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_histories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('commits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stars', sa.Integer(), server_default='0', nullable=False),
    sa.Column('forks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('repositories', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parsed_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commits >= 0', name='chk_github_histories_commits'),
    sa.CheckConstraint('forks >= 0', name='chk_github_histories_forks'),
    sa.CheckConstraint('repositories >= 0', name='chk_github_histories_repositories'),
    sa.CheckConstraint('stars >= 0', name='chk_github_histories_stars'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_github_histories_user_date')
    )
    op.create_index('idx_github_histories_user_date', 'github_histories', ['user_id', sa.literal_column('date DESC')], unique=False)
    op.create_table('leetcode_histories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('easy_solved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('medium_solved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hard_solved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('submissions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parsed_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('easy_solved >= 0', name='chk_leetcode_histories_easy_solved'),
    sa.CheckConstraint('hard_solved >= 0', name='chk_leetcode_histories_hard_solved'),
    sa.CheckConstraint('medium_solved >= 0', name='chk_leetcode_histories_medium_solved'),
    sa.CheckConstraint('problems_solved >= 0', name='chk_leetcode_histories_problems_solved'),
    sa.CheckConstraint('submissions >= 0', name='chk_leetcode_histories_submissions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_leetcode_histories_user_date')
    )
    op.create_index('idx_leetcode_histories_user_date', 'leetcode_histories', ['user_id', sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leetcode_histories_user_date', table_name='leetcode_histories')
    op.drop_table('leetcode_histories')
    op.drop_index('idx_github_histories_user_date', table_name='github_histories')
    op.drop_table('github_histories')
    # ### end Alembic commands ###
