import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import Date, DateTime, Float, ForeignKey, Index, String, desc
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.database import Base


class Insight(Base):
    """
    SQLAlchemy database model for the Insight entity.
    Stores a single structured insight generated by the Insights Engine
    for a user based on a comparison of current and historical analytics.
    """

    __tablename__ = "insights"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # --- Classification ---
    platform: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    metric_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    change_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    # --- Human-readable output ---
    message: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )

    # --- Numeric evidence ---
    current_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    historical_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    absolute_change: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    percent_change: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # --- Evidence period ---
    current_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
    )
    historical_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
    )

    # --- Rule versioning ---
    rule_version: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="v1",
        server_default="v1",
    )

    # --- Structured evidence / contextual metadata (e.g. {"baseline_zero": true}) ---
    evidence: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # --- Generation timestamp ---
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="insights")

    __table_args__ = (
        # Primary retrieval pattern: all insights for a user, newest first
        Index("idx_insights_user_generated", "user_id", desc("generated_at")),
        # Support filtering by platform for a user
        Index("idx_insights_user_platform", "user_id", "platform"),
    )
