import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, UniqueConstraint, desc
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.database import Base


class Recommendation(Base):
    """
    SQLAlchemy database model for the Recommendation entity.

    Stores a single actionable recommendation generated by the Rule-Based
    Recommendation Engine (Task 11.1) for a user.

    Unlike Insights (which are immutable comparison results), Recommendations
    are mutable: users may dismiss or complete them via the dashboard.
    The `status` column tracks this lifecycle.

    Deduplication key: (user_id, rule_id, rule_version)
    The Recommendation Orchestrator Service (Task 11.3) uses this key to
    prevent inserting multiple identical active recommendations per rule run.
    """

    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # --- Rule identification (from RecommendationCandidateSchema) ---
    rule_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    rule_version: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="v1",
        server_default="v1",
    )

    # --- Classification ---
    category: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    # "HIGH", "MEDIUM", or "LOW" — stored upper-case matching the rule engine output
    priority: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # --- Human-readable output ---
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    message: Mapped[str] = mapped_column(
        String(1000),
        nullable=False,
    )

    # --- Mutable lifecycle state ---
    # "active"   — newly generated and actionable
    # "dismissed" — user has acknowledged and dismissed the recommendation
    # "completed" — user has acted on the recommendation
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="active",
        server_default="active",
    )

    # --- Machine-readable evidence (why the rule fired) ---
    # Stores threshold values, actual metric values, etc. for debugging and
    # potential future adaptive thresholds. Nullable because a rule may produce
    # no additional context beyond its message.
    evidence: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # --- Timestamps ---
    # generated_at: when the recommendation was first created (immutable)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    # updated_at: tracks when status was last changed by the user or orchestrator
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="recommendations")

    __table_args__ = (
        # Enforce valid priority values (upper-case, matching rule engine output)
        CheckConstraint(
            "priority IN ('HIGH', 'MEDIUM', 'LOW')",
            name="chk_recommendations_priority",
        ),
        # Enforce valid status values
        CheckConstraint(
            "status IN ('active', 'dismissed', 'completed')",
            name="chk_recommendations_status",
        ),
        # Deduplication constraint — one active recommendation per user per rule version.
        # Task 11.3 uses this to upsert rather than insert blindly.
        UniqueConstraint(
            "user_id",
            "rule_id",
            "rule_version",
            name="uq_recommendations_user_rule",
        ),
        # Primary query pattern: active recommendations for a user, newest first
        Index("idx_recommendations_user_generated", "user_id", desc("generated_at")),
        # Status-filtered queries: "show me all active recommendations"
        Index("idx_recommendations_user_status", "user_id", "status"),
    )
